# GitHub actions workflow.
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Build+Test CI

on:
  push:
    branches: [main, gh-actions]
    tags: [v*]
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  build-test-posix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [gcc, clang]
        exclude:
          - os: macos-latest
            cc: gcc
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: make check
    - run: make install DESTDIR="${PWD}/root/"

  build-test-windows:
    strategy:
      matrix:
        os: [windows-latest]
        cc: [clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}.exe
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: ${CC} -o compress \
             -Wall \
             -DNOFUNCDEF -DUSERMEM=800000 -DREGISTERS=3 \
             -D_CRT_SECURE_NO_WARNINGS \
             compress.c
    - run: ./tests/runtests.sh
